openchs-server-api/src/main/java/org/openchs/service/IndividualService.java, openchs-server-api/src/main/java/org/openchs/web/IndividualController.java, openchs-server-api/src/main/java/org/openchs/web/request/EnrolmentContract.java, openchs-server-api/src/main/java/org/openchs/web/request/ProgramEncountersContract.java
API to fetch all program enrolments metadata
[https://app.zenhub.com/workspaces/avni-data-entry-app-5dee574a1d6415443d9b3deb/issues/avniproject/avni-server/64]
=>  [DataEntryApp API] #64 Program Enrolments Metadata

openchs-server-api/src/main/java/org/openchs/service/IndividualService.java, openchs-server-api/src/main/java/org/openchs/web/IndividualController.java, openchs-server-api/src/main/java/org/openchs/web/request/ConceptContract.java, openchs-server-api/src/main/java/org/openchs/web/request/EncounterContract.java, openchs-server-api/src/main/java/org/openchs/web/request/IndividualContract.java
ZenHub Id - https://app.zenhub.com/workspaces/avni-data-entry-app-5dee574a1d6415443d9b3deb/issues/avniproject/avni-server/65
=> 65 subject encounters

openchs-server-api/src/main/java/org/openchs/domain/Individual.java, openchs-server-api/src/main/java/org/openchs/service/IndividualService.java
=> [DataEntryApp] 57 -Relationship Bug Resolved

openchs-server-api/src/main/java/org/openchs/domain/CHSEntity.java, openchs-server-api/src/main/java/org/openchs/projection/ConceptProjection.java, openchs-server-api/src/main/java/org/openchs/web/FormController.java, openchs-server-api/src/main/java/org/openchs/web/request/CatchmentContract.java, openchs-server-api/src/main/java/org/openchs/web/request/application/FormContract.java, openchs-server-api/src/main/java/org/openchs/web/request/webapp/EncounterTypeContractWeb.java, openchs-server-api/src/main/java/org/openchs/web/request/webapp/ProgramContractWeb.java, openchs-server-api/src/main/java/org/openchs/web/request/webapp/SubjectTypeContractWeb.java
Added audit log details in the api.
=> #1093 | Add audit data to all entities

openchs-server-api/src/main/java/org/openchs/service/IndividualService.java, openchs-server-api/src/main/java/org/openchs/web/request/EncounterContract.java, openchs-server-api/src/main/java/org/openchs/web/request/IndividualContract.java, openchs-server-api/src/main/java/org/openchs/web/request/IndividualRelationshipTypeContract.java, openchs-server-api/src/main/java/org/openchs/web/request/ProgramEncountersContract.java, openchs-server-api/src/main/java/org/openchs/web/request/RelationshipContract.java, openchs-server-api/src/main/java/org/openchs/web/request/webapp/IndividualRelationContract.java
Code mofications as per avni models.
End to end tested with avni web app
=> [101 avni-server]Avni Json Response Changed for Subject Profile

openchs-server-api/src/main/java/org/openchs/service/RuleService.java, openchs-server-api/src/main/java/org/openchs/web/RestClient.java, openchs-server-api/src/main/java/org/openchs/web/RuleController.java, openchs-server-api/src/main/resources/application.properties
Added Rest Template to make Httpclient call from Java to Node
=> Rules Server POC from Java to Node

openchs-server-api/src/main/java/org/openchs/dao/AddressLevelTypeRepository.java, openchs-server-api/src/main/java/org/openchs/domain/AddressLevelType.java, openchs-server-api/src/main/java/org/openchs/web/OperationalModulesController.java
Added Lowest Level Address Information
=> 131 subject registration gaps

openchs-server-api/src/main/java/org/openchs/service/ProgramEnrolmentService.java, openchs-server-api/src/main/java/org/openchs/web/ProgramEnrolmentController.java
Fetch Program Enrolment By Uuid
=> [AVNI SERVER] #Program Enrolment By Uuid

openchs-server-api/src/main/java/org/openchs/dao/ProgramEncounterRepository.java, openchs-server-api/src/main/java/org/openchs/service/ProgramEncounterService.java, openchs-server-api/src/main/java/org/openchs/service/ProgramEnrolmentService.java, openchs-server-api/src/main/java/org/openchs/web/ProgramEncounterController.java, openchs-server-api/src/main/java/org/openchs/web/ProgramEnrolmentController.java, openchs-server-api/src/main/java/org/openchs/web/request/ProgramEncountersContract.java
1] To get all the visit details using id.
2] To get list of all completed visits encounter type and completed date
=> [AVNI SERVER] #CompletedVisits Fetch All and fetch encounter by uuid

openchs-server-api/src/main/java/org/openchs/common/EntityHelper.java, openchs-server-api/src/main/java/org/openchs/domain/RuleFailureLog.java, openchs-server-api/src/main/java/org/openchs/service/ProgramEncounterService.java, openchs-server-api/src/main/java/org/openchs/service/ProgramEnrolmentService.java, openchs-server-api/src/main/java/org/openchs/service/RuleService.java, openchs-server-api/src/main/java/org/openchs/web/AbstractController.java, openchs-server-api/src/main/java/org/openchs/web/ProgramEncounterController.java, openchs-server-api/src/main/java/org/openchs/web/ProgramEnrolmentController.java, openchs-server-api/src/main/java/org/openchs/web/RuleController.java, openchs-server-api/src/main/java/org/openchs/web/request/ProgramEncounterRequest.java, openchs-server-api/src/main/java/org/openchs/web/request/ProgramEnrolmentRequest.java, openchs-server-api/src/main/java/org/openchs/web/request/rules/RulesContractWrapper/ProgramEncounterContractWrapper.java, openchs-server-api/src/main/java/org/openchs/web/request/rules/RulesContractWrapper/ProgramEnrolmentContractWrapper.java, openchs-server-api/src/main/java/org/openchs/web/request/rules/RulesContractWrapper/VisitSchedule.java, openchs-server-api/src/main/java/org/openchs/web/request/rules/constant/EntityEnum.java, openchs-server-api/src/main/java/org/openchs/web/request/rules/constant/RuleEnum.java, openchs-server-api/src/main/java/org/openchs/web/request/rules/constant/WorkFlowTypeEnum.java, openchs-server-api/src/main/java/org/openchs/web/request/rules/constructWrappers/ProgramEncounterConstructionService.java, openchs-server-api/src/main/java/org/openchs/web/request/rules/constructWrappers/ProgramEnrolmentConstructionService.java, openchs-server-api/src/main/java/org/openchs/web/request/rules/response/RuleResponseEntity.java
Adding VisitScheduleRule for ProgramEnrolment and ProgramEncounter with modificaiton in Save API.
Adding endpoints Enum and code clearance
=> Visit Schedule Rule ProgramEnrolment and ProgramEncounter and Save

openchs-server-api/src/main/java/org/openchs/service/ProgramEncounterService.java
=> Encounter Bug and Resolved for visit schedule

openchs-server-api/src/main/java/org/openchs/service/RuleService.java, openchs-server-api/src/main/java/org/openchs/web/RestClient.java, openchs-server-api/src/main/java/org/openchs/web/RuleController.java, openchs-server-api/src/main/java/org/openchs/web/request/rules/response/RuleResponseEntity.java
Removed null from response entity to provide only not null values
Check added for url is present or not.If url not found then endpoint exception message is thrown,
=> Endpoints URL check added and removed null entityresponse rules

openchs-server-api/src/main/java/org/openchs/dao/IndividualRepository.java, openchs-server-api/src/main/java/org/openchs/dao/ProgramEncounterRepository.java, openchs-server-api/src/main/java/org/openchs/service/ProgramEnrolmentService.java, openchs-server-api/src/main/java/org/openchs/web/ProgramEnrolmentController.java
Bugs Resolved
Individual search FirstName LastName
Completed Visit id to uuid change.
=> [AVNI SERVER] Bugs Resolved Individual Search and Completed Visits id to uuid change

openchs-server-api/src/main/java/org/openchs/service/ProgramEncounterService.java, openchs-server-api/src/main/java/org/openchs/web/request/ProgramEncountersContract.java
Enrolment UUID added for program encounter view visit
=> enrolment UUID added for program encounter view visit

openchs-server-api/src/main/java/org/openchs/dao/EncounterRepository.java, openchs-server-api/src/main/java/org/openchs/service/EncounterService.java, openchs-server-api/src/main/java/org/openchs/service/IndividualService.java, openchs-server-api/src/main/java/org/openchs/service/ObservationService.java, openchs-server-api/src/main/java/org/openchs/service/ProgramEncounterService.java, openchs-server-api/src/main/java/org/openchs/service/ProgramEnrolmentService.java, openchs-server-api/src/main/java/org/openchs/web/EncounterController.java, openchs-server-api/src/main/java/org/openchs/web/IndividualController.java, openchs-server-api/src/main/java/org/openchs/web/request/EncounterContract.java
Created API for Completed Visits Encounter and View visits encounter.
=> [AVNI SERVER] Encounter Completed Visit and View visit

openchs-server-api/src/main/java/org/openchs/web/IndividualController.java
Only FullName, firstName and LastName sort for individual search
=> Only FullName, firstName and LastName sort for individual search

openchs-server-api/src/main/java/org/openchs/service/IndividualService.java
Non individual Gender Issue: to solve null pointer issue.
=> Non individual Gender Issue

openchs-server-api/src/main/java/org/openchs/dao/IndividualRepository.java
search API changes:
Get record from API start with provided string only.
=> search API changes

openchs-server-api/src/main/java/org/openchs/service/IndividualService.java
Encountertype uuid change for encounter requirement
=> encountertype uuid change

openchs-server-api/src/main/java/org/openchs/projection/FormElementGroupWebProjection.java, openchs-server-api/src/main/java/org/openchs/projection/FormElementWebProjection.java
view filter rule change to provide rule text
=> view filter rule change

.github/ISSUE_TEMPLATE/bug_report.md, openchs-server-api/src/main/java/org/openchs/service/IndividualService.java, openchs-server-api/src/main/java/org/openchs/web/IndividualRelationshipController.java
Individualrelationship delete API
=> Individualrelationship

openchs-server-api/src/main/java/org/openchs/dao/ConceptRepository.java, openchs-server-api/src/main/java/org/openchs/dao/LocationRepository.java, openchs-server-api/src/main/java/org/openchs/dao/OrganisationConfigRepository.java, openchs-server-api/src/main/java/org/openchs/dao/OrganisationRepository.java, openchs-server-api/src/main/java/org/openchs/service/AddressLevelService.java, openchs-server-api/src/main/java/org/openchs/service/ConceptService.java, openchs-server-api/src/main/java/org/openchs/service/IndividualService.java, openchs-server-api/src/main/java/org/openchs/service/OrganisationConfigService.java, openchs-server-api/src/main/java/org/openchs/web/ConceptController.java, openchs-server-api/src/main/java/org/openchs/web/LocationController.java, openchs-server-api/src/main/java/org/openchs/web/OrganisationConfigController.java, openchs-server-api/src/main/java/org/openchs/web/OrganisationConfigSearchController.java
Added organisation config and all location API.
=> Organisationcofigchanges

openchs-server-api/src/main/java/org/openchs/service/OrganisationConfigService.java
concept uuid exist or not check
=> concept uuid exist or not check

openchs-server-api/src/main/java/org/openchs/service/IndividualSearchService.java, openchs-server-api/src/main/java/org/openchs/web/IndividualController.java, openchs-server-api/src/main/java/org/openchs/web/request/EnrolmentContract.java, openchs-server-api/src/main/java/org/openchs/web/request/IndividualContract.java, openchs-server-api/src/main/resources/db/migration/R__Functions.sql, openchs-server-api/src/main/resources/db/migration/R__Views.sql
=> Search api approach2

openchs-server-api/src/main/java/org/openchs/service/IndividualSearchService.java, openchs-server-api/src/main/resources/db/migration/R__Functions.sql
=> db user role change

avni-server-api/src/main/java/org/avni/server/domain/SyncTelemetry.java, avni-server-api/src/main/resources/db/migration/V1_302__MoveAuditColumnsToSyncTelemetryTable.sql
=> audit fields added to sync telemetry

avni-server-api/src/main/java/org/avni/server/web/response/SubjectResponse.java
Modifies the /api/subject contract to send the catchments of the subject in response
=> Add. Catchments name in the subject API response

.circleci/config.yml
Update Docker image tag to `docker:git` in the workflow
=> Update Docker image tag to `docker:git` in the workflow

avni-server-api/src/main/java/org/avni/server/domain/OperationalEncounterType.java, avni-server-api/src/main/java/org/avni/server/domain/OperationalProgram.java, avni-server-api/src/main/java/org/avni/server/domain/OperationalSubjectType.java, avni-server-api/src/main/java/org/avni/server/domain/OrganisationAwareEntity.java, avni-server-api/src/test/java/org/avni/server/domain/OrganisationAwareEntityTest.java
#700 
Added LastModifiedBy in OperationalSubjectType
=> Added LastModifiedBy 

avni-server-api/src/main/java/org/avni/messaging/contract/UserContract.java, avni-server-api/src/main/java/org/avni/server/service/BulkUploadS3Service.java, avni-server-api/src/main/java/org/avni/server/service/CognitoIdpService.java, avni-server-api/src/main/java/org/avni/server/service/IdpServiceFactory.java, avni-server-api/src/main/java/org/avni/server/web/ImportController.java, avni-server-api/src/main/java/org/avni/server/web/request/UserContract.java, avni-server-api/src/main/java/org/avni/server/web/request/rules/RulesContractWrapper/UserContract.java
This PR fixes #707  the issues of bad data in system caused by Leading spaces when creating users .
=> #707 | Leading spaces when creating users are now trimmed!

avni-server-api/src/main/java/org/avni/server/service/DashboardService.java
fix for  issue avniproject/avni-webapp#1209
=> Rename the dashboard if it is voided to support the same name

avni-server-api/src/main/java/org/avni/server/service/EncounterTypeService.java
Fixes bug https://github.com/avniproject/avni-server/issues/872
=> #872 | Add immutable to importer
